# Generated by Django 5.1 on 2024-09-20 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_embrapii', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoInformacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('tipo_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('fonte_dados', models.CharField(blank=True, max_length=255, null=True)),
                ('ferramenta', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('user_atualizacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('user_registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
