# Generated by Django 5.1 on 2024-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_embrapii', '0002_produtoinformacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoinformacional',
            name='dono_produto',
            field=models.CharField(blank=True, choices=[('ged_dpg', 'GED/DPG'), ('nao_informado', 'Não Informado')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtoinformacional',
            name='status_privacidade',
            field=models.CharField(blank=True, choices=[('nao_informado', 'Não Informado'), ('publico', 'Público'), ('privado', 'Privado')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtoinformacional',
            name='ferramenta',
            field=models.CharField(blank=True, choices=[('ms_power_bi', 'Microsoft Power BI'), ('ms_excel', 'Microsoft Excel'), ('ms_word', 'Microsoft Word'), ('canva', 'Canva'), ('pdf', 'PDF'), ('google_looker', 'Google Looker'), ('nao_informado', 'Não Informado')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtoinformacional',
            name='fonte_dados',
            field=models.CharField(blank=True, choices=[('ged_dpg', 'GED/DPG'), ('nao_informado', 'Não Informado')], max_length=255, null=True),
        ),
    ]
