# Generated by Django 5.1 on 2024-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_embrapii', '0004_alter_produtoinformacional_dono_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_projeto', models.CharField(max_length=255, unique=True)),
                ('unidade_embrapii', models.CharField(blank=True, max_length=255, null=True)),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_projeto', models.TextField(blank=True, null=True)),
                ('parceria_programa', models.CharField(blank=True, max_length=255, null=True)),
                ('call', models.CharField(blank=True, max_length=255, null=True)),
                ('cooperacao_internacional', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidade_financiamento', models.CharField(blank=True, max_length=255, null=True)),
                ('uso_recurso_obrigatorio', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnologia_habilitadora', models.CharField(blank=True, max_length=255, null=True)),
                ('missoes_cndi', models.CharField(blank=True, max_length=255, null=True)),
                ('area_aplicacao', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('trl_inicial', models.CharField(blank=True, max_length=255, null=True)),
                ('trl_final', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_embrapii', models.FloatField(blank=True, null=True)),
                ('valor_empresa', models.FloatField(blank=True, null=True)),
                ('valor_unidade_embrapii', models.FloatField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo_publico', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('descricao_publica', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('nota_avaliacao', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('data_extracao_dados', models.DateField(blank=True, null=True)),
                ('status_view', models.BooleanField()),
            ],
        ),
    ]
